package com.mooncloak.kodetools.bulmak.modifier

public val isWhite: BulmaModifier = BulmaModifier(value = "is-white")
public val isBlack: BulmaModifier = BulmaModifier(value = "is-black")
public val isLight: BulmaModifier = BulmaModifier(value = "is-light")
public val isDark: BulmaModifier = BulmaModifier(value = "is-dark")
public val isText: BulmaModifier = BulmaModifier(value = "is-text")
public val isGhost: BulmaModifier = BulmaModifier(value = "is-ghost")

public val isPrimary: BulmaModifier = BulmaModifier(value = "is-primary")
public val isLink: BulmaModifier = BulmaModifier(value = "is-link")
public val isInfo: BulmaModifier = BulmaModifier(value = "is-info")
public val isSuccess: BulmaModifier = BulmaModifier(value = "is-success")
public val isWarning: BulmaModifier = BulmaModifier(value = "is-warning")
public val isDanger: BulmaModifier = BulmaModifier(value = "is-danger")

public val isSmall: BulmaModifier = BulmaModifier(value = "is-small")

// Size Modifiers:
// isDefault is deliberately left empty. The default doesn't have a CSS class value.
public val isDefault: BulmaModifier = BulmaModifier(value = "")
public val isNormal: BulmaModifier = BulmaModifier(value = "is-normal")
public val isMedium: BulmaModifier = BulmaModifier(value = "is-medium")
public val isLarge: BulmaModifier = BulmaModifier(value = "is-large")

// Image Size Modifiers:
public val is16x16: BulmaModifier = BulmaModifier(value = "is-16x16")
public val is24x24: BulmaModifier = BulmaModifier(value = "is-24x24")
public val is32x32: BulmaModifier = BulmaModifier(value = "is-32x32")
public val is48x48: BulmaModifier = BulmaModifier(value = "is-48x48")
public val is64x64: BulmaModifier = BulmaModifier(value = "is-64x64")
public val is96x96: BulmaModifier = BulmaModifier(value = "is-96x96")
public val is128x128: BulmaModifier = BulmaModifier(value = "is-128x128")

// Image Ratio Modifiers:
public val isSquare: BulmaModifier = BulmaModifier(value = "is-square")
public val is1by1: BulmaModifier = BulmaModifier(value = "is-1by1")
public val is5by4: BulmaModifier = BulmaModifier(value = "is-5by4")
public val is4by3: BulmaModifier = BulmaModifier(value = "is-4by3")
public val is3by2: BulmaModifier = BulmaModifier(value = "is-3by2")
public val is5by3: BulmaModifier = BulmaModifier(value = "is-5by3")
public val is16by9: BulmaModifier = BulmaModifier(value = "is-16by9")
public val is2by1: BulmaModifier = BulmaModifier(value = "is-2by1")
public val is3by1: BulmaModifier = BulmaModifier(value = "is-3by1")
public val is4by5: BulmaModifier = BulmaModifier(value = "is-4by5")
public val is3by4: BulmaModifier = BulmaModifier(value = "is-3by4")
public val is2by3: BulmaModifier = BulmaModifier(value = "is-2by3")
public val is3by5: BulmaModifier = BulmaModifier(value = "is-3by5")
public val is9by16: BulmaModifier = BulmaModifier(value = "is-9by16")
public val is1by2: BulmaModifier = BulmaModifier(value = "is-1by2")
public val is1by3: BulmaModifier = BulmaModifier(value = "is-1by3")
public val hasRatio: BulmaModifier = BulmaModifier(value = "has-ratio")

public val areSmall: BulmaModifier = BulmaModifier(value = "are-small")
public val areMedium: BulmaModifier = BulmaModifier(value = "are-medium")
public val areLarge: BulmaModifier = BulmaModifier(value = "are-large")

public val isResponsive: BulmaModifier = BulmaModifier(value = "is-responsive")
public val isFullWidth: BulmaModifier = BulmaModifier(value = "is-fullwidth")

public val isOutlined: BulmaModifier = BulmaModifier(value = "is-outlined")
public val isInverted: BulmaModifier = BulmaModifier(value = "is-inverted")
public val isRounded: BulmaModifier = BulmaModifier(value = "is-rounded")

public val isSelected: BulmaModifier = BulmaModifier(value = "is-selected")
public val isHovered: BulmaModifier = BulmaModifier(value = "is-hovered")
public val isFocused: BulmaModifier = BulmaModifier(value = "is-focused")
public val isActive: BulmaModifier = BulmaModifier(value = "is-active")
public val isLoading: BulmaModifier = BulmaModifier(value = "is-loading")
public val isStatic: BulmaModifier = BulmaModifier(value = "is-static")

public val isGrouped: BulmaModifier = BulmaModifier(value = "is-grouped")
public val isGroupedMultiline: BulmaModifier = BulmaModifier(value = "is-grouped-multiline")
public val hasAddOns: BulmaModifier = BulmaModifier(value = "has-addons")

public val isLeft: BulmaModifier = BulmaModifier(value = "is-left")
public val isCentered: BulmaModifier = BulmaModifier(value = "is-centered")
public val isRight: BulmaModifier = BulmaModifier(value = "is-right")

// List modifiers:
public val isLowerAlpha: BulmaModifier = BulmaModifier(value = "is-lower-alpha")
public val isLowerRoman: BulmaModifier = BulmaModifier(value = "is-lower-roman")
public val isUpperAlpha: BulmaModifier = BulmaModifier(value = "is-upper-alpha")
public val isUpperRoman: BulmaModifier = BulmaModifier(value = "is-upper-roman")

// Table Modifiers:
public val isBordered: BulmaModifier = BulmaModifier(value = "is-bordered")
public val isStriped: BulmaModifier = BulmaModifier(value = "is-striped")
public val isHoverable: BulmaModifier = BulmaModifier(value = "is-hoverable")

// Tag Modifiers:
public val isDelete: BulmaModifier = BulmaModifier(value = "is-delete")

// Title Modifiers:
public val title: BulmaModifier = BulmaModifier(value = "title")
public val subtitle: BulmaModifier = BulmaModifier(value = "subtitle")
public val is1: BulmaModifier = BulmaModifier(value = "is-1")
public val is2: BulmaModifier = BulmaModifier(value = "is-2")
public val is3: BulmaModifier = BulmaModifier(value = "is-3")
public val is4: BulmaModifier = BulmaModifier(value = "is-4")
public val is5: BulmaModifier = BulmaModifier(value = "is-5")
public val is6: BulmaModifier = BulmaModifier(value = "is-6")

// Form Modifiers:
public val hasIconsLeft: BulmaModifier = BulmaModifier(value = "has-icons-left")
public val hasIconsRight: BulmaModifier = BulmaModifier(value = "has-icons-right")
public val isExpanded: BulmaModifier = BulmaModifier(value = "is-expanded")
public val isHorizontal: BulmaModifier = BulmaModifier(value = "is-horizontal")
public val label: BulmaModifier = BulmaModifier(value = "label")
public val input: BulmaModifier = BulmaModifier(value = "input")
public val textarea: BulmaModifier = BulmaModifier(value = "textarea")
public val select: BulmaModifier = BulmaModifier(value = "select")
public val checkbox: BulmaModifier = BulmaModifier(value = "checkbox")
public val radio: BulmaModifier = BulmaModifier(value = "radio")
public val button: BulmaModifier = BulmaModifier(value = "button")
public val help: BulmaModifier = BulmaModifier(value = "help")
public val hasFixedSize: BulmaModifier = BulmaModifier(value = "has-fixed-size")
public val isMultiple: BulmaModifier = BulmaModifier(value = "is-multiple")
public val isBoxed: BulmaModifier = BulmaModifier(value = "is-boxed")
public val hasName: BulmaModifier = BulmaModifier(value = "has-name")

// Column Modifiers:
public val isThreeQuarters: BulmaModifier = BulmaModifier(value = "is-three-quarters")
public val isTwoThirds: BulmaModifier = BulmaModifier(value = "is-two-thirds")
public val isHalf: BulmaModifier = BulmaModifier(value = "is-half")
public val isOneThird: BulmaModifier = BulmaModifier(value = "is-one-third")
public val isOneQuarter: BulmaModifier = BulmaModifier(value = "is-one-quarter")
public val isFull: BulmaModifier = BulmaModifier(value = "is-full")
public val isFourFifths: BulmaModifier = BulmaModifier(value = "is-four-fifths")
public val isThreeFifths: BulmaModifier = BulmaModifier(value = "is-three-fifths")
public val isTwoFifths: BulmaModifier = BulmaModifier(value = "is-two-fifths")
public val isOneFifth: BulmaModifier = BulmaModifier(value = "is-one-fifth")

public val isOne: BulmaModifier = BulmaModifier(value = "is-1")
public val isTwo: BulmaModifier = BulmaModifier(value = "is-2")
public val isThree: BulmaModifier = BulmaModifier(value = "is-3")
public val isFour: BulmaModifier = BulmaModifier(value = "is-4")
public val isFive: BulmaModifier = BulmaModifier(value = "is-5")
public val isSix: BulmaModifier = BulmaModifier(value = "is-6")
public val isSeven: BulmaModifier = BulmaModifier(value = "is-7")
public val isEight: BulmaModifier = BulmaModifier(value = "is-8")
public val isNine: BulmaModifier = BulmaModifier(value = "is-9")
public val isTen: BulmaModifier = BulmaModifier(value = "is-10")
public val isEleven: BulmaModifier = BulmaModifier(value = "is-11")
public val isTwelve: BulmaModifier = BulmaModifier(value = "is-12")

public val isOffsetThreeQuarters: BulmaModifier = BulmaModifier(value = "is-offset-three-quarters")
public val isOffsetTwoThirds: BulmaModifier = BulmaModifier(value = "is-offset-two-thirds")
public val isOffsetHalf: BulmaModifier = BulmaModifier(value = "is-offset-half")
public val isOffsetOneThird: BulmaModifier = BulmaModifier(value = "is-offset-one-third")
public val isOffsetOneQuarter: BulmaModifier = BulmaModifier(value = "is-offset-one-quarter")
public val isOffsetFull: BulmaModifier = BulmaModifier(value = "is-offset-full")
public val isOffsetFourFifths: BulmaModifier = BulmaModifier(value = "is-offset-four-fifths")
public val isOffsetThreeFifths: BulmaModifier = BulmaModifier(value = "is-offset-three-fifths")
public val isOffsetTwoFifths: BulmaModifier = BulmaModifier(value = "is-offset-two-fifths")
public val isOffsetOneFifth: BulmaModifier = BulmaModifier(value = "is-offset-one-fifth")

public val isOffsetOne: BulmaModifier = BulmaModifier(value = "is-offset-1")
public val isOffsetTwo: BulmaModifier = BulmaModifier(value = "is-offset-2")
public val isOffsetThree: BulmaModifier = BulmaModifier(value = "is-offset-3")
public val isOffsetFour: BulmaModifier = BulmaModifier(value = "is-offset-4")
public val isOffsetFive: BulmaModifier = BulmaModifier(value = "is-offset-5")
public val isOffsetSix: BulmaModifier = BulmaModifier(value = "is-offset-6")
public val isOffsetSeven: BulmaModifier = BulmaModifier(value = "is-offset-7")
public val isOffsetEight: BulmaModifier = BulmaModifier(value = "is-offset-8")
public val isOffsetNine: BulmaModifier = BulmaModifier(value = "is-offset-9")
public val isOffsetTen: BulmaModifier = BulmaModifier(value = "is-offset-10")
public val isOffsetEleven: BulmaModifier = BulmaModifier(value = "is-offset-11")
public val isOffsetTwelve: BulmaModifier = BulmaModifier(value = "is-offset-12")

public val isNarrow: BulmaModifier = BulmaModifier(value = "is-narrow")
public val isNarrowMobile: BulmaModifier = BulmaModifier(value = "is-narrow-mobile")
public val isNarrowTablet: BulmaModifier = BulmaModifier(value = "is-narrow-tablet")
public val isNarrowTouch: BulmaModifier = BulmaModifier(value = "is-narrow-touch")
public val isNarrowDesktop: BulmaModifier = BulmaModifier(value = "is-narrow-desktop")
public val isNarrowWidescreen: BulmaModifier = BulmaModifier(value = "is-narrow-widescreen")
public val isNarrowFullhd: BulmaModifier = BulmaModifier(value = "is-narrow-fullhd")

public val isMobile: BulmaModifier = BulmaModifier(value = "is-mobile")
public val isTablet: BulmaModifier = BulmaModifier(value = "is-tablet")
public val isTouch: BulmaModifier = BulmaModifier(value = "is-touch")
public val isDesktop: BulmaModifier = BulmaModifier(value = "is-desktop")
public val isWidescreen: BulmaModifier = BulmaModifier(value = "is-widescreen")
public val isFullhd: BulmaModifier = BulmaModifier(value = "is-fullhd")

public val isGapless: BulmaModifier = BulmaModifier(value = "is-gapless")

public val isVerticallyCentered: BulmaModifier = BulmaModifier(value = "is-vccentered")

public val isColMin1: BulmaModifier = BulmaModifier(value = "is-col-min-1")
public val isColMin2: BulmaModifier = BulmaModifier(value = "is-col-min-2")
public val isColMin3: BulmaModifier = BulmaModifier(value = "is-col-min-3")
public val isColMin4: BulmaModifier = BulmaModifier(value = "is-col-min-4")
public val isColMin5: BulmaModifier = BulmaModifier(value = "is-col-min-5")
public val isColMin6: BulmaModifier = BulmaModifier(value = "is-col-min-6")
public val isColMin7: BulmaModifier = BulmaModifier(value = "is-col-min-7")
public val isColMin8: BulmaModifier = BulmaModifier(value = "is-col-min-8")
public val isColMin9: BulmaModifier = BulmaModifier(value = "is-col-min-9")
public val isColMin10: BulmaModifier = BulmaModifier(value = "is-col-min-10")
public val isColMin11: BulmaModifier = BulmaModifier(value = "is-col-min-11")
public val isColMin12: BulmaModifier = BulmaModifier(value = "is-col-min-12")
public val isColMin13: BulmaModifier = BulmaModifier(value = "is-col-min-13")
public val isColMin14: BulmaModifier = BulmaModifier(value = "is-col-min-14")
public val isColMin15: BulmaModifier = BulmaModifier(value = "is-col-min-15")
public val isColMin16: BulmaModifier = BulmaModifier(value = "is-col-min-16")
public val isColMin17: BulmaModifier = BulmaModifier(value = "is-col-min-17")
public val isColMin18: BulmaModifier = BulmaModifier(value = "is-col-min-18")
public val isColMin19: BulmaModifier = BulmaModifier(value = "is-col-min-19")
public val isColMin20: BulmaModifier = BulmaModifier(value = "is-col-min-20")
public val isColMin21: BulmaModifier = BulmaModifier(value = "is-col-min-21")
public val isColMin22: BulmaModifier = BulmaModifier(value = "is-col-min-22")
public val isColMin23: BulmaModifier = BulmaModifier(value = "is-col-min-23")
public val isColMin24: BulmaModifier = BulmaModifier(value = "is-col-min-24")
public val isColMin25: BulmaModifier = BulmaModifier(value = "is-col-min-25")
public val isColMin26: BulmaModifier = BulmaModifier(value = "is-col-min-26")
public val isColMin27: BulmaModifier = BulmaModifier(value = "is-col-min-27")
public val isColMin28: BulmaModifier = BulmaModifier(value = "is-col-min-28")
public val isColMin29: BulmaModifier = BulmaModifier(value = "is-col-min-29")
public val isColMin30: BulmaModifier = BulmaModifier(value = "is-col-min-30")
public val isColMin31: BulmaModifier = BulmaModifier(value = "is-col-min-31")
public val isColMin32: BulmaModifier = BulmaModifier(value = "is-col-min-32")

public val isGap0: BulmaModifier = BulmaModifier(value = "is-gap-0")
public val isGap1: BulmaModifier = BulmaModifier(value = "is-gap-1")
public val isGap2: BulmaModifier = BulmaModifier(value = "is-gap-2")
public val isGap3: BulmaModifier = BulmaModifier(value = "is-gap-3")
public val isGap4: BulmaModifier = BulmaModifier(value = "is-gap-4")
public val isGap5: BulmaModifier = BulmaModifier(value = "is-gap-5")
public val isGap6: BulmaModifier = BulmaModifier(value = "is-gap-6")
public val isGap7: BulmaModifier = BulmaModifier(value = "is-gap-7")
public val isGap8: BulmaModifier = BulmaModifier(value = "is-gap-8")

public val has0Cols: BulmaModifier = BulmaModifier(value = "has-0-cols")
public val has1Cols: BulmaModifier = BulmaModifier(value = "has-1-cols")
public val has2Cols: BulmaModifier = BulmaModifier(value = "has-2-cols")
public val has3Cols: BulmaModifier = BulmaModifier(value = "has-3-cols")
public val has4Cols: BulmaModifier = BulmaModifier(value = "has-4-cols")
public val has5Cols: BulmaModifier = BulmaModifier(value = "has-5-cols")
public val has6Cols: BulmaModifier = BulmaModifier(value = "has-6-cols")
public val has7Cols: BulmaModifier = BulmaModifier(value = "has-7-cols")
public val has8Cols: BulmaModifier = BulmaModifier(value = "has-8-cols")
public val has9Cols: BulmaModifier = BulmaModifier(value = "has-9-cols")
public val has10Cols: BulmaModifier = BulmaModifier(value = "has-10-cols")
public val has11Cols: BulmaModifier = BulmaModifier(value = "has-11-cols")
public val has12Cols: BulmaModifier = BulmaModifier(value = "has-12-cols")

public val hasAutoCount: BulmaModifier = BulmaModifier(value = "has-auto-count")

public val section: BulmaModifier = BulmaModifier(value = "section")

public val hasTextCentered: BulmaModifier = BulmaModifier(value = "has-text-centered")